#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This script contains methods to evaluate the results generated by
the classifier models in Test and Fit sub directories.
"""

def getRecall():
    # ToDo:
    return (0)

def getSpecificity():
    # ToDo:
    return (0)

def getAccuracy():
    # ToDo:
    return (0)

def getPrecision():
    # ToDo:
    return (0)

